### PR TITLE
Fixes issue #195 alerts user if they are trying to log in with an email not associated to a User

### PR DESCRIPTION
**Pull request by yeti-detective**
## Why is this PR needed?

Fixes [issue 195](https://github.com/CZagrobelny/new_sanctuary_asylum/issues/195)

## Solution

Since the Devise gem is used for session creation, I created an override of that controller with logic to check whether the given email address exists in the Users table.

This is a naive approach, as the Devise gem uses the Warden gem (a module, not a class) for authentication, and if the logic could be overridden on Warden it wouldn't require an extra database query. My Ruby is too rusty to figure out how to override a module method if that is possible.

### Link to associated issue: 
[Issue 195](https://github.com/CZagrobelny/new_sanctuary_asylum/issues/195)

### CODE REVIEW

**Comment by yeti-detective** [comment]
## Overview of my manual testing
### Here is a screenshot of a user logging in with an invalid email address:
invalid email

### Here is a screenshot of a user logging in with a valid email and invalid password:
validEmailBadPassword

### Here is a screenshot of a user logged in with a valid email and password:
successfulLogin

**Comment by yeti-detective** [comment]
rspec passing locally...

**Comment by rsl** [comment]
howdy. you should be able to redefine a module's method in the `User` class itself by defining it in that class _after_ you include the module [which happens in `Devise` case by the code here https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/models/user.rb#L5-L8 due to Ruby's "last method defined wins" strategy. overriding `Devise` this way is a pretty common thing to do [or at least i seem to work on projects that require doing it hehehe]. i like to leave a comment on the `devise` setup line and comment[s] on the redefined method itself.

**Comment by yeti-detective** [comment]
Awesome, @rsl thanks!

**Comment by yeti-detective** [comment]
Awesome, @rsl thanks!

**Comment by yeti-detective** [comment]
I am going to cancel this PR and take a different approach.

**Pull request closed without merging**
