### PR TITLE
Dockerize application

### PR DESCRIPTION
**Pull request by arieldiamond**
This PR should allow users to run this application from a docker container. It has only been tested on macs. To run: run `make` in your terminal. Please let me know if you run into any errors and I'll see if I can correct them. 

@sydneycodes and I paired on this at Write/Speak/Code.

### CODE REVIEW

**Comment by arieldiamond** [comment]
I am working on a make command to run rspec from the container, but currently `rspec` can only be run by execing into the container. I'm including instructions in the readme.

**Comment by CZagrobelny** [comment]
@arieldiamond and @sydneycodes sorry for the delay getting back to this!  The set up on Mac worked awesome!  I tested on Windows, and unfortunately it doesn't look like the 'make' command works on Windows:  https://github.com/mozilla/addons-server/issues/5495  BUT, I was able to get everything running on Windows using commands in the Makefile!  This is very exciting!!!

I have a couple changes for documentation and I am inclined to have the documentation take them through the steps of building and running (rather than the makefile, just for consistency in experience between operating systems), but I am interested in any thoughts you have on this!  The troubleshooting section was excellent!  When I went back to running the application locally, I did have to troubleshoot the change in the database.yml file ('db' rather than 'root').  I think this is something that would also be mitigated by having the user go through set up and instruct them to manually change the value in the database.yml file (would make it easier for them to recognize what changed in the file if they decided to switch and run it locally).

Let me know if you would like to continue to work on the PR/if you have the capacity to keep working on it with your current workload.  I am happy to pick it up and continue with the changes I'll list below! 

- [ ] Move the Docker instructions into it's own .md file
- [ ] Add a link to the Docker download page and tell readers to download/install as the first step in the Docker instructions 
- [ ] In the Readme, add a brief explanation of what Docker is and what running the application in Docker means.  As well as the link to the Docker instructions.
- [ ] Consider removing the Makefile and instead listing these steps and frequently used docker commands in the instructions

**Comment by sydneycodes** [comment]
Thanks @CZagrobelny I love all these suggestions. I will sync up with Ariel and we'll figure out a workstream for these.

**Comment by arieldiamond** [comment]
Alright @CZagrobelny! @sydneycodes and I updated the docs and added a new way for users to go between running the docker container and just running rails locally. Let us know if you want any other updates!

**Review by CZagrobelny — APPROVED** [review]
This looks great! @arieldiamond and @sydneycodes thank you so much for your work on this!! Merging presently!

**Pull request merged**
