### PR TITLE
Issue #195 invalid email take2

### PR DESCRIPTION
**Pull request by yeti-detective**
## Why is this PR needed?

After further research, I think my original approach was best. The [method](https://github.com/wardencommunity/warden/blob/master/lib/warden/proxy.rb#L328) I would need to override in Warden (which apparently runs before Rails even starts, so that may not work) in order to avoid the extra backend DB query is a private method anyway.
I also looked for options in [Devise](https://github.com/plataformatec/devise) for splitting the invalid login logic, and couldn't find anything.

## Solution

The solution was to override Devise' Session#create controller _(app/controllers/devise_overrides/sessions_controller.rb)_ method to set the flash_message to an invalid_email alert _(config/locales/devise.en.yml)_ if no `User` exists with the given email.

### Link to associated issue: 
[Issue 195](https://github.com/CZagrobelny/new_sanctuary_asylum/issues/195)

### CODE REVIEW

**Comment by yeti-detective** [comment]
I honestly don't know why Gemfile.lock and schema.rb are in this branch. :sob:

**Comment by rsl** [comment]
@yeti-detective what `bundle` command did you run to install the gems? i used to hit this and i think i was using `bundle update` instead of `bundle install`. i came from a path where we locked down gem versions hard so this was never an issue. until it was. lol ;)

**Comment by rsl** [comment]
also... i didn't look at the old solution but this solution seems perfectly normal to me too. i was more commenting on the general commonness of overriding methods in `User` [or whatever Devise is operating on].

**Comment by yeti-detective** [comment]
@rsl I am nearly certain I was using `bundle install`
I'm developing on Ubuntu, I wonder if that makes a difference in the gem versions vs someone developing on Mac.
BUT I was also certain that I only committed 3 files to git & here we are with 5 file changes, hm...

**Comment by yeti-detective** [comment]
I will fix the Gemfile.lock and schema.db as soon as I get home 👍

**Pull request merged**
