### PR TITLE
Updated to Ruby 2.6.4

### PR DESCRIPTION
**Pull request by bkuhlmann**
## Overview

Allows us to be running on the latest version of Ruby.

## Details

- [Ruby 2.6.3 Release Notes](https://is.gd/QOotAH) - Includes a unicode
  update and support for new Japanese era.
- [Ruby 2.6.4 Release Notes](https://is.gd/BWC7aJ) - Includes an RDoc
  security fix.

## Notes

I also deploy to Heroku using Ruby 2.6.4 so don't have any concerns using the latest version of Ruby.

### CODE REVIEW

**Comment by bkuhlmann** [comment]
:information_source: It looks like the build failed because a new build cache is needed but I don't have permission to do that. That's my initial guess, anyway. It's be interesting to run this again with the cache blown away:

CleanShot 2019-09-18 at 19 58 31@2x

**Comment by CZagrobelny** [comment]
@bkuhlmann re-built spec on CircleCI without cache. Still failing, unfortunately ☹️  https://circleci.com/gh/CZagrobelny/new_sanctuary_asylum/921
I don't have any great leads on what's going on there.  It does seem that phantom js is deprecated (https://discuss.circleci.com/t/phantomjs-on-circleci-2-0/10708) and that could be playing into this, but I haven't come across this specific issue of a version mismatch (that seemingly shouldn't be a mismatch).  I am not seeing these failures locally.

**Comment by bkuhlmann** [comment]
:bow: @CZagrobelny. Yeah, I'm surprised by this as well. Also, I can't reproduce locally either. The Ruby update should not affect Phantom.js so this is confusing behavior. 😅

**Comment by bkuhlmann** [comment]
:information_source: Closing this PR until I can sort out issues with Phantom.js. Will re-open once I have a solution.

**Pull request closed without merging**
