### PR TITLE
Feature/friends filter 1 year deadline

### PR DESCRIPTION
**Pull request by freen**
Hi. This is my first PR into the repository. Thanks as always for the opportunity to lend a hand. Warmly welcoming all critique and commentary.

Solidaridad 🖤 
Daniel

# Filters include watermarks / placeholders (not default values) before they're used

screen shot 2018-06-16 at 10 59 48 am

# jQuery UI Datepicker fires on field focus

screen shot 2018-06-16 at 10 59 57 am

# Backend search filter kicks in when both are populated

_(GET is made on input value change)_

screen shot 2018-06-16 at 10 59 19 am

# Filters can be used in tandem

screen shot 2018-06-16 at 10 59 28 am

# PR includes passing test coverage

```
➜  freen_new_sanctuary_asylum git:(feature/friends-filter-1-year-deadline) rspec spec/models/friend_spec.rb:91
Run options: include {:focus=>true, :locations=>{"./spec/models/friend_spec.rb"=>[91]}}

Randomized with seed 49511

Friend
  friends with their 1 year asylum application deadlines falling between two future boundaries, inclusive
    .asylum_deadlines_ending scope
      should return only the friends whose deadlines fall within the two boundaries, inclusive

Top 1 slowest examples (0.10995 seconds, 48.1% of total time):
  Friend friends with their 1 year asylum application deadlines falling between two future boundaries, inclusive .asylum_deadlines_ending scope should return only the friends whose deadlines fall within the two boundaries, inclusive
    0.10995 seconds ./spec/models/friend_spec.rb:93

Finished in 0.22854 seconds (files took 4.69 seconds to load)
1 example, 0 failures

Randomized with seed 49511

Coverage report generated for RSpec to /Users/bickett/src/freen_new_sanctuary_asylum/coverage. 61 / 1526 LOC (4.0%) covered.
```

### CODE REVIEW

**Comment by CZagrobelny** [comment]
@freen this is looking really good so far!  Thank you for all of the documentation in the PR description, so helpful!

I made a PR on your PR for a couple issues I discovered in QA:
1.  Running the app locally, the datetime picker js in the script tag in application.html.erb was not getting called (likely because it was not in a document.ready).  Moved it to our js file for admin friend search, which resolved that issue.
2. Search form was submitting if there was only one date value in the range.  Added some js to fix this.
PR is here:  https://github.com/freen/new_sanctuary_asylum/pull/1
Once you've reviewed, feel free to make any changes if you see an opportunity for cleanup or just merge into your branch.  After that point, will take another look through the PR to see if there is anything else before I approve the PR.  Thanks!!!!

**Comment by CZagrobelny** [comment]
@freen one additional thing, it looks like these changes broke a spec around making sure we keep search params after deleting a friend record:  spec/features/admin/delete_a_friend_spec.rb:33

**Comment by freen** [comment]
@CZagrobelny thanks for those fixes / enhancements!

Re: rspec failure -

When I began writing the test for my feature, I noticed that a number of the tests were failing at HEAD on master. My mistake was subsequently ignoring all other specs, during and after the completion of this feature.. hence I missed that I broke that spec! Thanks for pointing that out.

See my output in my gist here: https://gist.github.com/freen/175d88874dd66b4c48b4ca18c5fce51c

This also happens if I re-seed the database on master: https://gist.github.com/freen/b503f8d734ce86827d133c69d592ccd5

Example:

``` 
1) Admin invites a new user user accepting an invitation with invalid information does not sign in the user
     Failure/Error: end
     
     ArgumentError:
       SMTP From address may not be blank: nil
     # ./spec/features/invite_a_new_user_spec.rb:36:in `block (3 levels) in <top (required)>'
```

Are these failures "known" / "expected"? Or possibly a problem with my local dependencies? The funniest thing is I'm not able to find the actions or views or mailers corresponding to the "invite new user" functionality implied by the spec, so I wasn't having much luck yet digging into those test failures.

Some googling around [suggested that maybe the solution](https://stackoverflow.com/questions/45014520/rails-devise-with-gmail-errors) is to set a default "from" for emails sent in `test.rb`,  which did indeed fix all of the failing tests for me: https://github.com/CZagrobelny/new_sanctuary_asylum/pull/81/commits/ac06b19be65dfa18845be8bb8f277657613b1d08

But now I'm wondering if this isn't a "bad" bandaid. Won't production have the same exceptions? Are invite / lock out emails triggering exceptions at the moment on prod? Or do the SendGrid smtp settings somehow forgo this whole scenario which my test environment is encountering?

**Comment by CZagrobelny** [comment]
@freen apologies for the delay on this.  I was working on finishing up some big architectural changes and getting them merged!  Now that they are merged, my next priority to to get all the branches rebased on updated master to resolve the conflicts.  Will work on this next weekend, and then will QA, make any changes that are needed and hopefully get this work merged in at that point.  Will reach out if I have any questions during the rebase.  Thanks for your patience with this!

**Comment by CZagrobelny** [comment]
@freen I have rebased this work and pushed a new branch with a couple tweaks:  https://github.com/CZagrobelny/new_sanctuary_asylum/pull/87
Just need to do a final QA/review before merge.  Closing this PR since I have a new branch with the rebased work.

**Pull request closed without merging**
